// 根据已检查的样例版式建立脱敏模板，不复制公司、银行账户或历史交易。
import fs from 'node:fs/promises';
import {Workbook, SpreadsheetFile} from '@oai/artifact-tool';
const wb = Workbook.create();
const s = wb.worksheets.add('对账单');
s.showGridLines = false;
const widths = [7,12,18,37,7,12,13,17,26,29,20];
widths.forEach((w,i) => s.getRangeByIndexes(0,i,18,1).format.columnWidth = w);
s.getRange('A1:K18').format.font = {name:'宋体',size:11};
s.getRange('A1:K18').format.rowHeight = 25;
s.getRange('A1:K18').format.verticalAlignment = 'center';
for(const range of ['A1:K1','A2:K2','A3:F3','G3:K3','A4:F4','G4:K4','B5:K5','A9:G9','A10:G10','A11:G11','A12:K12','A13:K13','A14:F14','G14:K14','A15:F15','G15:K15','A16:F16','G16:K16','A17:F17','G17:K17']) s.mergeCells(range);
s.getRange('A1').values=[['供应方名称']];
s.getRange('A2').values=[['对账单']];
s.getRange('A1:K2').format.font={name:'宋体',size:18};
s.getRange('A1:K2').format.horizontalAlignment='center';
s.getRange('A1:K2').format.rowHeight=32;
s.getRange('A3').values=[['TO：客户名称']];
s.getRange('G3').values=[['FM：供应方']];
s.getRange('A4').values=[['TEL：']]; s.getRange('G4').values=[['TEL：']];
s.getRange('B5').values=[['核对日期：']];
s.getRange('B5:K5').format.horizontalAlignment='right';
s.getRange('A6:K6').values=[['序号','日期','送货单号','品名及规格','单位','数量','单价','金额','备注','报价单商品序号','送货单商品序号']];
s.getRange('A6:K8').format.borders={preset:'all',style:'thin',color:'#000000'};
s.getRange('A6:K8').format.horizontalAlignment='center';
s.getRange('A6:K8').format.wrapText=true;
s.getRange('G7:H8').setNumberFormat('#,##0.00###');
s.getRange('A9').values=[['合计（大写）：']];
s.getRange('A10').values=[['税额（仅对未含税报价按确认税率计算）：']];
s.getRange('A11').values=[['含税合计：']];
s.getRange('A12').values=[['结算说明：']];
s.getRange('G14').values=[['制表人：']];
s.getRange('A15').values=[['账户名称：']]; s.getRange('G15').values=[['核对人：']];
s.getRange('A16').values=[['账户号码：']]; s.getRange('G16').values=[['审核：']];
s.getRange('G17').values=[['审批：']];
wb.recalculate();
await fs.mkdir('assets',{recursive:true});
const output=await SpreadsheetFile.exportXlsx(wb); await output.save('assets/statement-template.xlsx');
